### ISSUE TITLE
[Lesson 3] 새로운 Pattern

### ISSUE THREAD

**Issue by Choiyos** [JeongHwa1217/devTutorial#4]
# [Lesson 3] 새로운 Pattern

아래의 2 가지 Pattern 을 추가하고 (총 3 개의 Pattern 이 된다)
사용자가 원하는 Pattern 을 선택할 수 있도록 한다. 

```
- Pattern 추가
*****
 ****
  ***
   **
    * 
 
- Pattern 추가
   *
  ***
 *****
  ***
   * 
```

- 제한사항
  - 잘못된 Input 이 들어오면 다시 입력을 받도록 한다.
  - Input 입력방법은 정해져 있지 않다.
  - 사용자가 이해하기 쉬운 것을 제안한다
  - 다이아몬드 형태의 입력은 홀수만 입력되도록 한다.
  - 정상적으로 선택한 후 종료한다.

**Comment by Choiyos** [comment]
아래의 경우는 의도된 사용성일까요?
![image](https://user-images.githubusercontent.com/31244245/166924118-f626e02c-8b12-4df5-b27c-161436590d86.png)

**Comment by Choiyos** [comment]
오른쪽위의 경우 많은 별 출력시 스타일이 꺾이는 현상이 있습니다.
![image](https://user-images.githubusercontent.com/31244245/166924192-434c6c4d-825a-4aae-a64e-afedd6b48817.png)

**Comment by Choiyos** [comment]
다이아몬드 패턴도 비슷한 이슈가 있네요.
![image](https://user-images.githubusercontent.com/31244245/166924257-4b3502b5-94dc-4bfe-baed-306b471af4b7.png)

**Comment by JeongHwa1217** [comment]
> 아래의 경우는 의도된 사용성일까요? ![image](https://user-images.githubusercontent.com/31244245/166924118-f626e02c-8b12-4df5-b27c-161436590d86.png)

의도한 바는 아니나, html input type = number의 경우 floating number를 지원하여 1e+2=100으로 변환되어 지원되는 것 같습니다.
참고 : [https://html.spec.whatwg.org/multipage/input.html#number-state-(type%3Dnumber)](url)

e를 막기 위한 방법으로는 아래와 같이 숫자가 아닌 문자열을 직접 제거하는 방법이 있습니다.
const check = /[^0-9]/g; 
string = string.replace(check, "");

**Comment by Choiyos** [comment]
수고하셨습니다!
