### ISSUE TITLE
[Lesson 4] Pattern 추가 

### ISSUE THREAD

**Issue by Choiyos** [JeongHwa1217/devTutorial#5]
# [Lesson 4] Pattern 추가 

아래의 Pattern 을 추가한다. 
 
```
- Pattern 추가
   ***
  ***
 *** 
 
- Pattern 추가
   ***
  **
 * 
```

- 제한사항
  - 사용자가 이해하기 쉬운 화면을 제안한다.
  - 화면에 출력되는 Pattern의 생성을 Vue에서 하는것이 아닌, Spring Boot프로젝트에서 생성하여 결괏값만 Vue에서 표현한다.
  - Vue와 Spring Boot간의 데이터 교환 방식은 자유롭게 정한다.

**Comment by Choiyos** [comment]
혹시 package.json에 axios가 추가가 되어있는게 맞나요?
또한 vue프로젝트의 빌드가 정상적으로 되나요? @JeongHwa1217

**Comment by Choiyos** [comment]
Vue프로젝트만 빌드하고, Spring프로젝트는 빌드하지 않은 상태에서 별을 출력하려는 시도를 하면 별도의 오류가 뜨지 않아 어떤 상황인지 알기 어렵네요.
서버와의 통신이 불안정할때에 대한 안내를 해주면 좋을 것 같아요!

**Comment by JeongHwa1217** [comment]
dependency에 axios 추가 및 서버 통신 불가시 alert 메세지 띄우도록 수정 반영 완료하였습니다.

**Comment by Choiyos** [comment]
수고하셨습니다 ^^
